ACCESSION: "LA03136E71"
RAGTAG_REF: "/project/gbru_wheat2/ref/Attraktion_ENA/Attraktion.rename.fasta"
TREP_FASTA: "/project/gbru_wheat2/ref/TREP/trep-db_nr_Rel-19.fasta"
VECSCREEN_DB: "files/UniVec"
VRN_DB: "files/TripleDirkC_vrn_genes.fa"
PPD_DB: "files/Taes_Ppd_genes.fa"
