GENOTYPE: "LA03136E71"
PACBIO_DIR: "/90daydata/gbru_wheat2/PacBio_WGS/LA03136E71"
RAGTAG_REF: "/project/gbru_wheat2/ref/Raz_assemblies/Gina/250925_Hilliard_pseudomolecules_v1+unanchored_contigs_filtered_chloroplast.fasta"
